version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: sudo apt-get update

      # Restore bundle cache
      - restore_cache:
          keys:
          - movierental-{{ checksum "pom.xml" }}

      - run: mvn clean compile

      - save_cache:
          paths:
            - ~/.maven
          key: movierental-{{ checksum "pom.xml" }}

      # run tests
      - run:
          name: test
          command: |
              mvn test

  deploy-to-qa:
      machine: true
      steps:
        - checkout
        - deploy:
            name: Deploy Master to QA
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                mvn test
              fi

  staging:
        machine: true
        steps:
          - checkout
          - deploy:
              name: Deploy Master to Staging
              command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  mvn test
                fi

workflows:
  version: 2
  deploy-movie-rental:
    jobs:
      - build
      - deploy-to-qa:
          requires:
            - build
      - deploy-to-staging:
          type: approval
          requires:
            - deploy-to-qa
      - staging:
          requires:
            - deploy-to-staging